(* ::Section:: *)
(* Effective-model support for the D30 source route *)

(* Communicates with:
   - src/core/setup.wl through CasimirSubs and the globally initialized
     FeynArts/FeynCalc environment.
   - src/core/kinematics_and_utilities.wl through KinematicRules,
     SafeDoPolarizationSums, and ApplyFeynCalcRules.
   - src/core/profiles.wl through D30EffectiveModelName[], which is referenced
     in the D30 profile metadata.
   - src/routes/massive_a30_unintegrated.wl and
     src/routes/massive_a30_reconstruction.wl, which use the effective-source
     interference objects as the D30-specific physics input.

   Why this file exists:
   D30 is not generated by the same plain massless source used for the A/B/C
   families.  The project therefore isolates the model-dependent source
   generation here so the rest of the pipeline can treat the resulting
   self-interference as just another antenna building block.  This separation
   keeps D30-specific physics assumptions from leaking into generic route code. *)

D30EffectiveModelDirectory::usage =
  "D30EffectiveModelDirectory[] returns the repo-local directory containing the effective FeynArts model files for the D30 source process.";

D30EffectiveModelName::usage =
  "D30EffectiveModelName[] returns the classes-model name used for the repo-local D30 source model.";

D30EffectiveGenericModelName::usage =
  "D30EffectiveGenericModelName[] returns the generic-model name used for the repo-local D30 source model.";

EnsureD30EffectiveModelPath::usage =
  "EnsureD30EffectiveModelPath[] prepends the repo-local D30 effective-model directory to $ModelPath when needed and returns the directory path.";

D30EffectiveModelSpec::usage =
  "D30EffectiveModelSpec[] returns an association describing the repo-local D30 effective FeynArts model.";

D30EffectiveModelFilesExistQ::usage =
  "D30EffectiveModelFilesExistQ[] returns True when the repo-local D30 effective model files are present.";

D30EffectiveSourceInsertions::usage =
  "D30EffectiveSourceInsertions[numFinalParticles] generates the tree-level FeynArts field insertions for the neutralino source process in the repo-local D30 effective model.";

D30EffectiveSourceAmplitude::usage =
  "D30EffectiveSourceAmplitude[numFinalParticles] generates the converted FeynCalc amplitude for the neutralino source process in the repo-local D30 effective model.";

D30SourcePolarizationCanonicalize::usage =
  "D30SourcePolarizationCanonicalize[expr] rewrites the source-model polarization labels to the outgoing-momentum convention expected by the package summation helpers.";

D30SourceCanonicalKinematicRules::usage =
  "D30SourceCanonicalKinematicRules[numFinalParticles] returns the additional source-process scalar-product rules involving the incoming neutralino momentum p.";

D30SourceMassRules::usage =
  "D30SourceMassRules[] returns the source-process mass substitutions used to reach the massless D30 source convention.";

D30SourceAmplitudeTerms::usage =
  "D30SourceAmplitudeTerms[numFinalParticles] returns the expanded source-amplitude terms used by the D30 source-interference builder.";

D30SourceAmplitudeTermGroups::usage =
  "D30SourceAmplitudeTermGroups[] returns the current hand-identified grouping of the D30 1->3 source-amplitude terms into the contact, gluino-exchange, and gluon-exchange sectors.";

D30SourceAmplitudeGroupAssociation::usage =
  "D30SourceAmplitudeGroupAssociation[] returns an association that exposes the grouped D30 1->3 source-amplitude terms sector by sector.";

D30SourceRenameSUNIndices::usage =
  "D30SourceRenameSUNIndices[expr, numFinalParticles] renames only the internal SUN indices in one source amplitude copy so self-interference products do not violate Einstein summation while the external colour labels still contract between the two copies.";

D30SourceWardContractedAmplitude::usage =
  "D30SourceWardContractedAmplitude[gluonIndex] replaces one external source-gluon polarization vector by its momentum in the D30 1->3 source amplitude, returning the resulting amplitude-level Ward probe.";

D30SourceWardGroupAssociation::usage =
  "D30SourceWardGroupAssociation[gluonIndex] returns the grouped D30 source-amplitude sectors after the selected external gluon polarization has been replaced by its momentum.";

D30SourceWardGroupZeroQAssociation::usage =
  "D30SourceWardGroupZeroQAssociation[gluonIndex] returns the current zero/nonzero status of each grouped D30 Ward-contracted source-amplitude sector after the standard D30 kinematic substitutions.";

D30SourceWardIdentityZeroQ::usage =
  "D30SourceWardIdentityZeroQ[gluonIndex] tests whether the corresponding D30 source Ward-contracted amplitude vanishes after the current canonicalization steps.";

D30SourceWardStageAssociation::usage =
  "D30SourceWardStageAssociation[gluonIndex] returns the staged D30 Ward probe after each canonicalization step used during source-route debugging.";

D30SourceWardGroupStageAssociation::usage =
  "D30SourceWardGroupStageAssociation[gluonIndex] returns the staged Ward probes for each grouped D30 source-amplitude sector.";

D30SourceRouteReadyQ::usage =
  "D30SourceRouteReadyQ[diagnostics] returns True only when the D30 source-model build diagnostics satisfy the hard activation gates for the public build route.";

D30SourceWardReduce::usage =
  "D30SourceWardReduce[expr] applies the D30-specific momentum-conservation and Dirac-chain cleanup used by the Ward diagnostics.";

D30SourceInterferencePair::usage =
  "D30SourceInterferencePair[leftTerm, rightTerm, numFinalParticles] evaluates one source-model interference pair for the D30 reconstruction track.";

D30SourceSelfInterference::usage =
  "D30SourceSelfInterference[numFinalParticles] builds the summed source-model self-interference for the D30 reconstruction track.";

D30SourcePolarizationSum::usage =
  "D30SourcePolarizationSum[expr, numFinalParticles] applies the physical final-state gluon polarization sums used by the D30 source-model route.";

D30SourceParityOddTraceRules::usage =
  "D30SourceParityOddTraceRules[] returns the D30-specific rule that drops the parity-odd four-gamma gamma5 traces after the source momentum is identified with the sum of the three massless final-state momenta.";

D30SourceDenominatorRules::usage =
  "D30SourceDenominatorRules[] returns the explicit D30 source-propagator substitutions that map the remaining source-model denominator channels to the package invariant language.";

D30SourceBridgeExpression::usage =
  "D30SourceBridgeExpression[expr, numFinalParticles] applies the current D30 source-to-antenna convention bridge to a built source expression.";

D30SourceBridgeStageAssociation::usage =
  "D30SourceBridgeStageAssociation[expr, numFinalParticles] returns the staged D30 source-to-antenna bridge so intermediate residuals can be inspected.";

D30SourceAntennaCandidate::usage =
  "D30SourceAntennaCandidate[bornInterference, productionInterference] returns the current source-derived D30 antenna candidate obtained after the explicit auxiliary-source bridge.";


(* D30EffectiveModelDirectory[]
   ============================
   Summary
     Return the repository-local directory containing the D30 effective-model
     files.

   Returns
     String
       Absolute path to the `models/` directory.

   Notes
     Keeping the model path repo-local makes the D30 route reproducible across
     machines without requiring a global FeynArts installation to be modified. *)
D30EffectiveModelDirectory[] :=
  FileNameJoin[{$AntennaPipelineRoot, "models"}];

(* D30EffectiveModelName[]
   =======================
   Summary
     Return the classes-model name for the D30 effective source.

   Returns
     String
       FeynArts model name.

   Notes
     This stays as a helper rather than a string literal so the profile layer
     and route layer can reference the same source of truth. *)
D30EffectiveModelName[] :=
  "D30Effective";

(* D30EffectiveGenericModelName[]
   ==============================
   Summary
     Return the generic-model name paired with the D30 effective source model.

   Returns
     String
       FeynArts generic-model name. *)
D30EffectiveGenericModelName[] :=
  "D30Effective";

(* EnsureD30EffectiveModelPath[]
   =============================
   Summary
     Ensure that the repository-local D30 model directory appears on
     `$ModelPath`.

   Returns
     String
       The model directory that was ensured.

   Notes
     This is side-effectful because FeynArts resolves models globally.  The
     helper prepends the repo-local model so the package uses the validated
     version even if the user has another model with the same name elsewhere. *)
EnsureD30EffectiveModelPath[] :=
  Module[{modelDir},
    modelDir = D30EffectiveModelDirectory[];
    If[!MemberQ[$ModelPath, modelDir],
      PrependTo[$ModelPath, modelDir]
    ];
    modelDir
  ];

(* D30EffectiveModelSpec[]
   =======================
   Summary
     Return the resolved specification of the D30 effective model.

   Returns
     Association
       Directory, model names, and expected model file paths.

   Notes
     Packaging this information into one association makes later validation and
     amplitude generation code less brittle than repeating string concatenation
     at every call site. *)
D30EffectiveModelSpec[] :=
  <|
    "Directory" -> EnsureD30EffectiveModelPath[],
    "Model" -> D30EffectiveModelName[],
    "GenericModel" -> D30EffectiveGenericModelName[],
    "ModelFile" -> FileNameJoin[{D30EffectiveModelDirectory[],
      D30EffectiveModelName[] <> ".mod"}],
    "GenericFile" -> FileNameJoin[{D30EffectiveModelDirectory[],
      D30EffectiveGenericModelName[] <> ".gen"}]
  |>;

(* D30EffectiveModelFilesExistQ[]
   ==============================
   Summary
     Test whether the local D30 model files are actually present.

   Returns
     Boolean
       `True` when both the classes and generic files exist.

   Notes
     This is kept separate from path installation so diagnostics can distinguish
     “path not configured” from “files genuinely absent.” *)
D30EffectiveModelFilesExistQ[] :=
  Module[{spec},
    spec = D30EffectiveModelSpec[];
    AllTrue[{spec["ModelFile"], spec["GenericFile"]}, FileExistsQ]
  ];

(* D30EffectiveSourceInsertions[numFinalParticles]
   ===============================================
   Summary
     Build the FeynArts field insertions for the D30 effective source process.

   Parameters
     numFinalParticles : Integer
       Supported values are `2` and `3`, corresponding to the source processes
       needed for the D30 reconstruction track.

   Returns
     FeynArts insertion structure
       The inserted tree topologies for the neutralino source decay.

   Notes
     The final state is generated from the physics content of the effective
     source model rather than by reusing the generic antenna source.  That is
     the core design reason this file exists at all. *)
D30EffectiveSourceInsertions[numFinalParticles_Integer /;
    MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{spec, finalState},
    spec = D30EffectiveModelSpec[];
    finalState = Join[{F[2], V[1]}, Table[V[1], {numFinalParticles - 2}]];
    InsertFields[
      CreateTopologies[0, 1 -> numFinalParticles],
      {F[1]} -> finalState,
      InsertionLevel -> {Classes},
      Model -> spec["Model"],
      GenericModel -> spec["GenericModel"]
    ]
  ];

(* D30EffectiveSourceAmplitude[numFinalParticles]
   ==============================================
   Summary
     Convert the inserted D30 effective-source diagrams into one FeynCalc
     amplitude.

   Parameters
     numFinalParticles : Integer
       Supported final-state multiplicity of the source process.

   Returns
     expression
       Converted FeynCalc amplitude.

   Notes
     The conversion uses outgoing `k1`, `k2`, ... labels and a single incoming
     source momentum `p` so the later kinematic bridge to antenna invariants is
     explicit and readable. *)
D30EffectiveSourceAmplitude[numFinalParticles_Integer /;
    MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{insertions, outMoms},
    insertions = D30EffectiveSourceInsertions[numFinalParticles];
    outMoms = Table[Symbol["k" <> ToString[i]], {i, 1, numFinalParticles}];
    FCFAConvert[
      CreateFeynAmp[insertions],
      IncomingMomenta -> {p},
      OutgoingMomenta -> outMoms,
      UndoChiralSplittings -> True,
      ChangeDimension -> D,
      List -> False,
      SMP -> True,
      Contract -> True,
      DropSumOver -> True
    ]
  ];

(* D30SourcePolarizationCanonicalize[expr]
   =======================================
   Summary
     Rewrite source-model polarization labels into the outgoing-momentum
     convention used elsewhere in the package.

   Parameters
     expr : expression
       D30 source amplitude or subexpression.

   Returns
     expression
       Canonicalized expression.

   Notes
     This is a convention bridge.  The underlying physics is unchanged, but the
     software needs one consistent sign convention so the generic polarization
     and kinematic helpers can be reused without D30-specific branches. *)
D30SourcePolarizationCanonicalize[expr_] :=
  expr /. Polarization[-mom_, phase_] :> Polarization[mom, phase];

(* D30SourceCanonicalKinematicRules[numFinalParticles]
   ===================================================
   Summary
     Return the additional scalar-product identities involving the incoming
     source momentum `p`.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     list
       Replacement rules from `Pair[p, ki]` structures to antenna invariants.

   Notes
     These rules are written explicitly rather than derived on the fly because
     they define the physics bridge from the source-process picture to the
     massless antenna invariant language used by the rest of the code base. *)
D30SourceCanonicalKinematicRules[2] :=
  {
    Pair[Momentum[p, _], Momentum[p, _]] -> q2,
    Pair[Momentum[p, _], Momentum[k1, _]] -> q2 / 2,
    Pair[Momentum[k1, _], Momentum[p, _]] -> q2 / 2,
    Pair[Momentum[p, _], Momentum[k2, _]] -> q2 / 2,
    Pair[Momentum[k2, _], Momentum[p, _]] -> q2 / 2
  };

D30SourceCanonicalKinematicRules[3] :=
  {
    q2 -> s12 + s13 + s23,
    Pair[Momentum[p, _], Momentum[p, _]] -> s12 + s13 + s23,
    Pair[Momentum[p, _], Momentum[k1, _]] -> (s12 + s13) / 2,
    Pair[Momentum[k1, _], Momentum[p, _]] -> (s12 + s13) / 2,
    Pair[Momentum[p, _], Momentum[k2, _]] -> (s12 + s23) / 2,
    Pair[Momentum[k2, _], Momentum[p, _]] -> (s12 + s23) / 2,
    Pair[Momentum[p, _], Momentum[k3, _]] -> (s13 + s23) / 2,
    Pair[Momentum[k3, _], Momentum[p, _]] -> (s13 + s23) / 2
  };

D30SourceCanonicalKinematicRules[_] :=
  {};

(* D30SourceMassRules[]
   ====================
   Summary
     Return the source-process mass substitutions used in the D30 convention
     bridge.

   Returns
     list
       Rules that set the gluino mass to zero and identify the neutralino mass
       squared with `q2`.

   Notes
     The D30 effective source is only an intermediate construction device.  The
     route ultimately targets a massless antenna convention, so these
     substitutions make that limiting interpretation explicit. *)
D30SourceMassRules[] :=
  {MGl -> 0, MNeu^2 -> q2};

(* D30SourceAmplitudeTerms[numFinalParticles]
   ==========================================
   Summary
     Expand the source amplitude into individual terms for pairwise
     self-interference construction.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     list
       Expanded amplitude terms.

   Notes
     The route interferes terms pairwise so diagonal and off-diagonal
     contributions can be counted transparently.  That is physically useful
     when debugging which interference channel is responsible for a mismatch. *)
D30SourceAmplitudeTerms[numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  AmplitudeTerms[
    Expand[D30SourcePolarizationCanonicalize[D30EffectiveSourceAmplitude[
      numFinalParticles]]]
  ];

(* D30SourceAmplitudeTermGroups[]
   ==============================
   Summary
     Return the current term-group map for the `1 -> 3` D30 source amplitude.

   Returns
     Association
       Mapping from readable group labels to term positions in
       `D30SourceAmplitudeTerms[3]`.

   Notes
     The grouping is intentionally explicit rather than reconstructed from
     pattern matching every time.  At the current stage of the D30 track, the
     main use of the amplitude is physics debugging, and readable stable labels
     are more valuable than clever automatic classification. *)
D30SourceAmplitudeTermGroups[] :=
  <|
    "Contact" -> {1},
    "GluinoExchange" -> {2, 3},
    "GluonExchange" -> {4, 5, 6, 7, 8}
  |>;

(* D30SourceAmplitudeGroupAssociation[]
   ====================================
   Summary
     Return the grouped `1 -> 3` D30 source-amplitude sectors.

   Returns
     Association
       Group label -> grouped amplitude expression.

   Notes
     This helper exists so future D30 debugging can work sector by sector
     without having to remember the current term ordering by hand.  That is a
     software ergonomics choice motivated by the present physics problem: we
     need to know whether a mismatch sits in the contact term, the gluino
     exchange, or the gluon exchange sector. *)
D30SourceAmplitudeGroupAssociation[] :=
  Module[{terms, groups},
    terms = D30SourceAmplitudeTerms[3];
    groups = D30SourceAmplitudeTermGroups[];
    Association @ KeyValueMap[#1 -> Total[terms[[#2]]]&, groups]
  ];

(* D30SourceRenameSUNIndices[expr, numFinalParticles]
   ==================================================
   Summary
     Rename only the internal colour indices in one copy of a source amplitude
     before multiplying it by another copy.

   Parameters
     expr : expression
       One amplitude term or amplitude copy.
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Expression with fresh SUN indices.

   Notes
     This is a software fix for a real colour-algebra issue: without distinct
     dummy indices, self-interference products can violate Einstein summation
     assumptions and produce spurious contractions.  However, the external
     gluon colour labels must be shared between the left and right amplitude
     copies so the physical external-colour sum still happens.  We therefore
     protect those external labels and rename only the genuinely internal
     dummy indices. *)
D30SourceRenameSUNIndices[expr_,
   numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{indices, protectedIndices, rules},
    indices =
      DeleteDuplicates[
        Cases[
          expr,
          head_Symbol[sym_Symbol] /; SymbolName[head] === "SUNIndex" :>
            head[sym],
          Infinity
        ]
      ];
    protectedIndices =
      (SUNIndex /@ Table[
        Symbol["Glu" <> ToString[i]],
        {i, 2, numFinalParticles + 1}
      ]);
    rules =
      Thread[
        Complement[indices, protectedIndices] ->
          (Complement[indices, protectedIndices] /. head_[sym_Symbol] :>
            head[Unique[SymbolName[sym] <> "$r"]])
      ];
    expr /. rules
  ];

(* D30SourcePolarizationSum[expr, numFinalParticles]
   =================================================
   Summary
     Apply the physical polarization sums appropriate to the D30 source route.

   Parameters
     expr : expression
       Source interference contribution before final-state gluon sums.
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Expression with the source-process gluon polarizations summed.

   Notes
     The effective D30 source emits real final-state gluons, not a virtual
     current like the A-family photon source.  We therefore use transverse
     reference-vector sums here rather than `VirtualBoson -> True`.  This is a
     physics choice, not just a simplification trick. *)
D30SourcePolarizationSum[expr_, 2] :=
  SafeDoPolarizationSums[expr, k2, p];

D30SourcePolarizationSum[expr_, 3] :=
  SafeDoPolarizationSums[
    SafeDoPolarizationSums[expr, k2, k3],
    k3,
    k2
  ];

D30SourcePolarizationSum[expr_, _] :=
  expr;

(* D30SourceWardContractedExpression[expr, gluonIndex]
   ===================================================
   Internal helper used by the D30 Ward diagnostics.

   Replace one selected external polarization object by its momentum while
   preserving the surrounding FeynCalc momentum wrapper used by FCFAConvert. *)
D30SourceWardContractedExpression[expr_, gluonIndex_Integer] :=
  Module[{momentum},
    momentum = Symbol["k" <> ToString[gluonIndex]];
    expr /. {
      Momentum[Polarization[momentum, phase_.], dim_.] :>
        Momentum[momentum, dim],
      Polarization[momentum, phase_.] :> momentum
    }
  ];

(* D30SourceWardContractedAmplitude[gluonIndex]
   ============================================
   Summary
     Build the amplitude-level Ward probe for one of the final-state source
     gluons.

   Parameters
     gluonIndex : Integer
       Supported values are `2` and `3`, matching the D30 `1 -> 3` source
       final-state gluons.

   Returns
     expression
       Source amplitude with the chosen polarization vector replaced by its
       momentum.

   Notes
     This is a deliberately low-level diagnostic object.  The D30 route is
     presently blocked by a source-model mismatch, so exposing the Ward probe
     directly makes the gauge-consistency question inspectable without forcing
     users to reconstruct it by hand from the raw amplitude. *)
D30SourceWardContractedAmplitude[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{amp},
    amp = D30SourcePolarizationCanonicalize[D30EffectiveSourceAmplitude[3]];
    D30SourceWardContractedExpression[amp, gluonIndex]
  ];

D30SourceWardStageAssociation[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{amp, raw, polarized, massed, kinematic, dimensional},
    amp = D30SourcePolarizationCanonicalize[D30EffectiveSourceAmplitude[3]];
    raw = D30SourceWardContractedExpression[amp, gluonIndex];
    polarized = raw;
    massed = polarized /. D30SourceMassRules[];
    kinematic = massed /. D30SourceCanonicalKinematicRules[3];
    dimensional = Expand[kinematic /. D -> 4 - 2 Epsilon];
    <|
      "Raw" -> raw,
      "PolarizationCanonicalized" -> polarized,
      "MassRulesApplied" -> massed,
      "CanonicalKinematicsApplied" -> kinematic,
      "DimensionalExpanded" -> dimensional,
      "BridgeApplied" -> D30SourceBridgeStageAssociation[dimensional, 3][
        "Expanded"]
    |>
  ];

D30SourceWardGroupStageAssociation[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{groups},
    groups = D30SourceAmplitudeGroupAssociation[];
    Association @ KeyValueMap[
      (#1 -> Module[{sector, raw, polarized, massed, kinematic, dimensional},
          sector = D30SourcePolarizationCanonicalize[#2];
          raw = D30SourceWardContractedExpression[sector, gluonIndex];
          polarized = raw;
          massed = polarized /. D30SourceMassRules[];
          kinematic = massed /. D30SourceCanonicalKinematicRules[3];
          dimensional = Expand[kinematic /. D -> 4 - 2 Epsilon];
          <|
            "Raw" -> raw,
            "PolarizationCanonicalized" -> polarized,
            "MassRulesApplied" -> massed,
            "CanonicalKinematicsApplied" -> kinematic,
            "DimensionalExpanded" -> dimensional,
            "BridgeApplied" -> D30SourceBridgeStageAssociation[
              dimensional, 3]["Expanded"]
          |>
        ])&,
      groups
    ]
  ];

(* D30SourceWardGroupAssociation[gluonIndex]
   =========================================
   Summary
     Return the grouped D30 source-amplitude sectors after one Ward
     contraction.

   Parameters
     gluonIndex : Integer
       Supported values are `2` and `3`.

   Returns
     Association
       Group label -> Ward-contracted grouped source amplitude.

   Notes
     This helper exists for D30 debugging rather than the public route.  The
     immediate question is not only whether the full Ward probe fails, but
     which source sector is responsible for the failure. *)
D30SourceWardGroupAssociation[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{groups},
    groups = D30SourceAmplitudeGroupAssociation[];
    Association @ KeyValueMap[
      (#1 -> D30SourceWardContractedExpression[#2, gluonIndex])&,
      groups
    ]
  ];

(* D30SourceWardGroupZeroQAssociation[gluonIndex]
   ==============================================
   Summary
     Return the current zero/nonzero status of each Ward-contracted D30 source
     sector.

   Parameters
     gluonIndex : Integer
       Supported values are `2` and `3`.

   Returns
     Association
       Group label -> Boolean zero test after the current canonicalization
       steps.

   Notes
     The same substitutions used by D30SourceWardIdentityZeroQ[...] are applied
     here so the grouped readout stays consistent with the full-route gate. *)
D30SourceWardGroupZeroQAssociation[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{groups, canonicalizeProbe},
    groups = D30SourceWardGroupAssociation[gluonIndex];
    canonicalizeProbe[expr_] :=
      expr //
      ReplaceAll[D30SourceMassRules[]] //
      ReplaceAll[D30SourceCanonicalKinematicRules[3]] //
      ReplaceAll[D -> 4] //
      D30SourceWardReduce;
    Association @ KeyValueMap[
      (#1 -> TrueQ[
        canonicalizeProbe[#2] === 0 ||
        Simplify[canonicalizeProbe[#2] == 0]
      ])&,
      groups
    ]
  ];

(* D30SourceWardIdentityZeroQ[gluonIndex]
   ======================================
   Summary
     Test whether the amplitude-level Ward probe currently vanishes.

   Parameters
     gluonIndex : Integer
       Supported values are `2` and `3`.

   Returns
     Boolean
       `True` only when the current canonicalized Ward-contracted amplitude
       simplifies to zero.

   Notes
     This helper is intentionally strict.  Returning `False` is not treated as
     a harmless numerical mismatch; for the D30 reconstruction track it is a
     meaningful indicator that the effective source model still needs physics
     scrutiny before the public antenna route can be promoted. *)
D30SourceWardIdentityZeroQ[gluonIndex_Integer /; MemberQ[{2, 3},
    gluonIndex]] :=
  Module[{probe},
    probe =
      D30SourceWardContractedAmplitude[gluonIndex] //
      ReplaceAll[D30SourceMassRules[]] //
      ReplaceAll[D30SourceCanonicalKinematicRules[3]] //
      ReplaceAll[D -> 4] //
      D30SourceWardReduce;
    TrueQ[probe === 0 || Simplify[probe == 0]]
  ];

D30SourceWardReduce[expr_] :=
  Module[{reduced},
    reduced =
      expr //
      ReplaceAll[{
        Momentum[p, dim_.] :>
          Momentum[k1 + k2 + k3, dim],
        Momentum[-p, dim_.] :>
          Momentum[-k1 - k2 - k3, dim]
      }] //
      FeynCalc`DiracSigmaExplicit //
      FeynCalc`DiracSimplify //
      Expand //
      FeynCalc`ChangeDimension[#, 4]& //
      FeynCalc`Contract //
      FeynCalc`DiracSimplify //
      Expand;
    reduced
  ];

(* D30SourceRouteReadyQ[diagnostics]
   =================================
   Summary
     Evaluate the hard source-model acceptance gates for the public D30 build
     route.

   Parameters
     diagnostics : Association
       Diagnostics returned by the D30 source-route build data.

   Returns
     Boolean
       `True` only when every required model, interference, and paper-match
       gate is satisfied.

   Notes
     Keeping this gate in one helper prevents the public activation policy from
     being duplicated across the build router, dev scripts, and future runtime
     checks. *)
D30SourceRouteReadyQ[diagnostics_Association] :=
  TrueQ @ And[
    Lookup[diagnostics, "SourceBornAmplitudeBuilt", False],
    Lookup[diagnostics, "SourceProductionAmplitudeBuilt", False],
    Lookup[diagnostics, "OrderedBornPartialBuilt", False],
    Lookup[diagnostics, "OrderedProductionPartialBuilt", False],
    Lookup[diagnostics, "OrderedAntennaExactMatchQ", False],
    Lookup[diagnostics, "ExchangedOrderedAntennaExactMatchQ", False],
    Lookup[diagnostics, "SourceCandidateExactMatchQ", False]
  ];

(* D30SourceParityOddTraceRules[]
   ==============================
   Summary
     Return the D30-specific parity-odd trace rules used in the auxiliary
     source bridge.

   Returns
     list
       Replacement rules setting the four-gamma gamma5 source traces to zero.

   Notes
     After the D30 source kinematics are imposed, the incoming source momentum
     satisfies `p = k1 + k2 + k3` with all final-state momenta massless.  The
     parity-odd traces therefore reduce to Levi-Civita contractions of four
     linearly dependent vectors and vanish identically.  Making that step
     explicit keeps the source bridge readable and auditable. *)
D30SourceParityOddTraceRules[] :=
  {
    DiracTrace[
      chain___ .
      DiracGamma[Momentum[a_, _], _] .
      DiracGamma[5] .
      tail___
    ] /; SubsetQ[{k1, k2, k3, p},
      DeleteDuplicates[Cases[{chain, DiracGamma[Momentum[a, D], D], tail},
        DiracGamma[Momentum[mom_, _], _] :> mom, Infinity]]
    ] :> 0,

    DiracTrace[
      DiracGamma[Momentum[a_, _], _] .
      DiracGamma[Momentum[b_, _], _] .
      DiracGamma[Momentum[c_, _], _] .
      DiracGamma[Momentum[p, _], _] .
      DiracGamma[5]
    ] /; Sort[{a, b, c}] === Sort[{k1, k2, k3}] :> 0,

    DiracTrace[
      DiracGamma[Momentum[p, _], _] .
      DiracGamma[Momentum[a_, _], _] .
      DiracGamma[Momentum[b_, _], _] .
      DiracGamma[Momentum[c_, _], _] .
      DiracGamma[5]
    ] /; Sort[{a, b, c}] === Sort[{k1, k2, k3}] :> 0
  };

D30SourceBridgeStageAssociation[expr_,
   numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{parityOddRemoved, denominatorsMapped, casimirReduced,
     epsilonProjected, combined, simplified, expanded},
    parityOddRemoved = expr /. D30SourceParityOddTraceRules[];
    denominatorsMapped = parityOddRemoved /. D30SourceDenominatorRules[];
    casimirReduced = denominatorsMapped /. CasimirSubs;
    epsilonProjected = casimirReduced /. Epsilon -> 0;
    combined = Together[epsilonProjected];
    simplified = Simplify[combined];
    expanded = Expand[simplified];
    <|
      "Input" -> expr,
      "ParityOddRemoved" -> parityOddRemoved,
      "DenominatorsMapped" -> denominatorsMapped,
      "CasimirReduced" -> casimirReduced,
      "EpsilonProjected" -> epsilonProjected,
      "Together" -> combined,
      "Simplified" -> simplified,
      "Expanded" -> expanded
    |>
  ];

(* D30SourceDenominatorRules[]
   ===========================
   Summary
     Return the remaining explicit source-propagator substitutions used by the
     D30 auxiliary-source bridge.

   Returns
     list
       Rules mapping the surviving source channels onto `s12` and `s13`.

   Notes
     After the main FeynCalc normalization pass, the D30 source route still
     leaves two explicit propagator channels visible.  Calling them out here
     makes the last source-to-antenna convention step explicit rather than
     relying on more opaque downstream simplification. *)
D30SourceDenominatorRules[] :=
  {
    FeynAmpDenominator[
      PropagatorDenominator[-Momentum[k1, _] - Momentum[k2, _], 0]
    ] -> 1 / s12,
    FeynAmpDenominator[
      PropagatorDenominator[-Momentum[k1, _] - Momentum[k3, _], 0]
    ] -> 1 / s13,
    FeynAmpDenominator[
      PropagatorDenominator[
        Plus[Times[-1, Momentum[k1, _]], Times[-1, Momentum[k2, _]]],
        0
      ]
    ] -> 1 / s12,
    FeynAmpDenominator[
      PropagatorDenominator[
        Plus[Times[-1, Momentum[k1, _]], Times[-1, Momentum[k3, _]]],
        0
      ]
    ] -> 1 / s13
  };

(* D30SourceBridgeExpression[expr, numFinalParticles]
   ==================================================
   Summary
     Apply the current explicit D30 source-to-antenna convention bridge.

   Parameters
     expr : expression
       Source-side amplitude or interference object.
     numFinalParticles : Integer
       Source multiplicity carried by the object.

   Returns
     expression
       Bridged source expression in the package invariant language.

   Notes
     This helper packages the current state of the legitimate D30 bridge:
     physical polarization bookkeeping has already happened upstream, colour is
     reduced, parity-odd source traces are removed for the kinematic reason
     explained above, the leftover source denominators are mapped to invariants,
     and the final result is projected onto the four-dimensional tree-level
     convention used by the encoded D30 paper target. *)
D30SourceBridgeExpression[expr_, numFinalParticles_Integer /; MemberQ[{2, 3},
    numFinalParticles]] :=
  D30SourceBridgeStageAssociation[expr, numFinalParticles]["Expanded"];

(* D30SourceAntennaCandidate[bornInterference, productionInterference]
   ===================================================================
   Summary
     Return the current source-derived D30 antenna candidate.

   Parameters
     bornInterference : expression
       D30 source `1 -> 2` self-interference.
     productionInterference : expression
       D30 source `1 -> 3` self-interference.

   Returns
     expression
       Current D30 antenna candidate obtained from the explicit source bridge.

   Notes
     The ratio strips the common source coupling through the `1 -> 2`
     normalization and then removes the extra strong coupling and adjoint color
     factor of the extra emitted gluon.  This is the physically motivated
     source candidate we compare to the literature.  It is intentionally named
     a candidate because the final paper-validated D30 bridge is not yet fully
     closed. *)
D30SourceAntennaCandidate[bornInterference_, productionInterference_] :=
  D30SourceBridgeExpression[productionInterference, 3] /
    (D30SourceBridgeExpression[bornInterference, 2] SUNN SMP["g_s"]^2) //
  Together //
  Simplify //
  Expand;

(* D30SourceInterferencePair[leftTerm, rightTerm, numFinalParticles]
   =================================================================
   Summary
     Evaluate one interference contribution between two source-amplitude terms.

   Parameters
     leftTerm, rightTerm : expression
       Source-amplitude terms to interfere.
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Simplified interference contribution in the package’s antenna
       kinematic convention.

   Notes
     This is the heart of the D30 effective-source bridge.  The function
     deliberately follows the same physical sequence one would write by hand:
     choose kinematics, form the conjugate product, perform colour and spin
     sums, sum physical gluon polarizations, then convert to the canonical
     invariant convention.  Keeping that order visible is more valuable here
     than maximizing terseness. *)
D30SourceInterferencePair[leftTerm_, rightTerm_,
   numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{left, bare, summed, polarized, expanded, evaluated,
     final},
    KinematicRules[numFinalParticles];
    (* Rename indices only on one side of the product so the resulting colour
       contractions represent the intended independent amplitude copies. *)
    left = D30SourceRenameSUNIndices[leftTerm, numFinalParticles];
    bare = ComplexConjugate[left] * rightTerm;
    (* Perform colour simplification before the polarization algebra gets too
       large.  This is mainly a usability and performance decision: smaller
       intermediate expressions are much easier to diagnose later. *)
    summed =
      bare //
      SUNSimplify[#, Explicit -> True, SUNNToCACF -> False]& //
      FermionSpinSum;
    polarized =
      D30SourcePolarizationSum[
        D30SourcePolarizationCanonicalize[summed],
        numFinalParticles
      ];
    expanded = DiracSigmaExplicit[polarized];
    evaluated = Calc[expanded];
    (* The final replacement chain is the bridge from the source-model algebra
       to the same invariant and epsilon convention used by the rest of the
       antenna package, so D30 can share diagnostics and route infrastructure
       with the A/B/C families. *)
    final =
      evaluated //
      ApplyFeynCalcRules[#, numFinalParticles]& //
      ReplaceAll[D30SourceCanonicalKinematicRules[numFinalParticles]] //
      ReplaceAll[D30SourceMassRules[]] //
      ReplaceAll[CasimirSubs] //
      ReplaceAll[D -> 4 - 2 Epsilon] //
      SUNSimplify //
      ReplaceAll[CasimirSubs] //
      Together;
    final
  ];

(* D30SourceSelfInterference[numFinalParticles]
   ============================================
   Summary
     Build the full D30 source self-interference by summing diagonal and
     off-diagonal term pairs.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Full source self-interference in canonical package form.

   Notes
     The diagonal/off-diagonal split is explicit on purpose.  Physically it
     mirrors the decomposition of |M|^2 into squares plus interference pieces,
     and software-wise it makes later debugging much easier than hiding the same
     combinatorics inside one double sum. *)
D30SourceSelfInterference[numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{terms, nTerms, diagonal, offDiagonal, result},
    terms = D30SourceAmplitudeTerms[numFinalParticles];
    nTerms = Length[terms];
    diagonal =
      Sum[
        D30SourceInterferencePair[terms[[i]], terms[[i]], numFinalParticles],
        {i, 1, nTerms}
      ];
    offDiagonal =
      Sum[
        2 D30SourceInterferencePair[terms[[i]], terms[[j]], numFinalParticles],
        {i, 1, nTerms - 1},
        {j, i + 1, nTerms}
      ];
    result =
      diagonal + offDiagonal //
      SUNSimplify //
      Together;
    result
  ];
