(* ::Section:: *)
(* Effective-model support for the D30 source route *)

(* Communicates with:
   - src/core/setup.wl through CasimirSubs and the globally initialized
     FeynArts/FeynCalc environment.
   - src/core/kinematics_and_utilities.wl through KinematicRules,
     SafeDoPolarizationSums, and ApplyFeynCalcRules.
   - src/core/profiles.wl through D30EffectiveModelName[], which is referenced
     in the D30 profile metadata.
   - src/routes/massive_a30_unintegrated.wl and
     src/routes/massive_a30_reconstruction.wl, which use the effective-source
     interference objects as the D30-specific physics input.

   Why this file exists:
   D30 is not generated by the same plain massless source used for the A/B/C
   families.  The project therefore isolates the model-dependent source
   generation here so the rest of the pipeline can treat the resulting
   self-interference as just another antenna building block.  This separation
   keeps D30-specific physics assumptions from leaking into generic route code. *)

D30EffectiveModelDirectory::usage =
  "D30EffectiveModelDirectory[] returns the repo-local directory containing the effective FeynArts model files for the D30 source process.";

D30EffectiveModelName::usage =
  "D30EffectiveModelName[] returns the classes-model name used for the repo-local D30 source model.";

D30EffectiveGenericModelName::usage =
  "D30EffectiveGenericModelName[] returns the generic-model name used for the repo-local D30 source model.";

EnsureD30EffectiveModelPath::usage =
  "EnsureD30EffectiveModelPath[] prepends the repo-local D30 effective-model directory to $ModelPath when needed and returns the directory path.";

D30EffectiveModelSpec::usage =
  "D30EffectiveModelSpec[] returns an association describing the repo-local D30 effective FeynArts model.";

D30EffectiveModelFilesExistQ::usage =
  "D30EffectiveModelFilesExistQ[] returns True when the repo-local D30 effective model files are present.";

D30EffectiveSourceInsertions::usage =
  "D30EffectiveSourceInsertions[numFinalParticles] generates the tree-level FeynArts field insertions for the neutralino source process in the repo-local D30 effective model.";

D30EffectiveSourceAmplitude::usage =
  "D30EffectiveSourceAmplitude[numFinalParticles] generates the converted FeynCalc amplitude for the neutralino source process in the repo-local D30 effective model.";

D30SourcePolarizationCanonicalize::usage =
  "D30SourcePolarizationCanonicalize[expr] rewrites the source-model polarization labels to the outgoing-momentum convention expected by the package summation helpers.";

D30SourceCanonicalKinematicRules::usage =
  "D30SourceCanonicalKinematicRules[numFinalParticles] returns the additional source-process scalar-product rules involving the incoming neutralino momentum p.";

D30SourceMassRules::usage =
  "D30SourceMassRules[] returns the source-process mass substitutions used to reach the massless D30 source convention.";

D30SourceAmplitudeTerms::usage =
  "D30SourceAmplitudeTerms[numFinalParticles] returns the expanded source-amplitude terms used by the D30 source-interference builder.";

D30SourceRenameSUNIndices::usage =
  "D30SourceRenameSUNIndices[expr] renames the explicit SUN indices in one source amplitude copy so self-interference products do not violate Einstein summation.";

D30SourceInterferencePair::usage =
  "D30SourceInterferencePair[leftTerm, rightTerm, numFinalParticles] evaluates one source-model interference pair for the D30 reconstruction track.";

D30SourceSelfInterference::usage =
  "D30SourceSelfInterference[numFinalParticles] builds the summed source-model self-interference for the D30 reconstruction track.";

(* D30EffectiveModelDirectory[]
   ============================
   Summary
     Return the repository-local directory containing the D30 effective-model
     files.

   Returns
     String
       Absolute path to the `models/` directory.

   Notes
     Keeping the model path repo-local makes the D30 route reproducible across
     machines without requiring a global FeynArts installation to be modified. *)
D30EffectiveModelDirectory[] :=
  FileNameJoin[{$AntennaPipelineRoot, "models"}];

(* D30EffectiveModelName[]
   =======================
   Summary
     Return the classes-model name for the D30 effective source.

   Returns
     String
       FeynArts model name.

   Notes
     This stays as a helper rather than a string literal so the profile layer
     and route layer can reference the same source of truth. *)
D30EffectiveModelName[] :=
  "D30Effective";

(* D30EffectiveGenericModelName[]
   ==============================
   Summary
     Return the generic-model name paired with the D30 effective source model.

   Returns
     String
       FeynArts generic-model name. *)
D30EffectiveGenericModelName[] :=
  "D30Effective";

(* EnsureD30EffectiveModelPath[]
   =============================
   Summary
     Ensure that the repository-local D30 model directory appears on
     `$ModelPath`.

   Returns
     String
       The model directory that was ensured.

   Notes
     This is side-effectful because FeynArts resolves models globally.  The
     helper prepends the repo-local model so the package uses the validated
     version even if the user has another model with the same name elsewhere. *)
EnsureD30EffectiveModelPath[] :=
  Module[{modelDir},
    modelDir = D30EffectiveModelDirectory[];
    If[!MemberQ[$ModelPath, modelDir],
      PrependTo[$ModelPath, modelDir]
    ];
    modelDir
  ];

(* D30EffectiveModelSpec[]
   =======================
   Summary
     Return the resolved specification of the D30 effective model.

   Returns
     Association
       Directory, model names, and expected model file paths.

   Notes
     Packaging this information into one association makes later validation and
     amplitude generation code less brittle than repeating string concatenation
     at every call site. *)
D30EffectiveModelSpec[] :=
  <|
    "Directory" -> EnsureD30EffectiveModelPath[],
    "Model" -> D30EffectiveModelName[],
    "GenericModel" -> D30EffectiveGenericModelName[],
    "ModelFile" -> FileNameJoin[{D30EffectiveModelDirectory[],
      D30EffectiveModelName[] <> ".mod"}],
    "GenericFile" -> FileNameJoin[{D30EffectiveModelDirectory[],
      D30EffectiveGenericModelName[] <> ".gen"}]
  |>;

(* D30EffectiveModelFilesExistQ[]
   ==============================
   Summary
     Test whether the local D30 model files are actually present.

   Returns
     Boolean
       `True` when both the classes and generic files exist.

   Notes
     This is kept separate from path installation so diagnostics can distinguish
     “path not configured” from “files genuinely absent.” *)
D30EffectiveModelFilesExistQ[] :=
  Module[{spec},
    spec = D30EffectiveModelSpec[];
    AllTrue[{spec["ModelFile"], spec["GenericFile"]}, FileExistsQ]
  ];

(* D30EffectiveSourceInsertions[numFinalParticles]
   ===============================================
   Summary
     Build the FeynArts field insertions for the D30 effective source process.

   Parameters
     numFinalParticles : Integer
       Supported values are `2` and `3`, corresponding to the source processes
       needed for the D30 reconstruction track.

   Returns
     FeynArts insertion structure
       The inserted tree topologies for the neutralino source decay.

   Notes
     The final state is generated from the physics content of the effective
     source model rather than by reusing the generic antenna source.  That is
     the core design reason this file exists at all. *)
D30EffectiveSourceInsertions[numFinalParticles_Integer /;
    MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{spec, finalState},
    spec = D30EffectiveModelSpec[];
    finalState = Join[{F[2], V[1]}, Table[V[1], {numFinalParticles - 2}]];
    InsertFields[
      CreateTopologies[0, 1 -> numFinalParticles],
      {F[1]} -> finalState,
      InsertionLevel -> {Classes},
      Model -> spec["Model"],
      GenericModel -> spec["GenericModel"]
    ]
  ];

(* D30EffectiveSourceAmplitude[numFinalParticles]
   ==============================================
   Summary
     Convert the inserted D30 effective-source diagrams into one FeynCalc
     amplitude.

   Parameters
     numFinalParticles : Integer
       Supported final-state multiplicity of the source process.

   Returns
     expression
       Converted FeynCalc amplitude.

   Notes
     The conversion uses outgoing `k1`, `k2`, ... labels and a single incoming
     source momentum `p` so the later kinematic bridge to antenna invariants is
     explicit and readable. *)
D30EffectiveSourceAmplitude[numFinalParticles_Integer /;
    MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{insertions, outMoms},
    insertions = D30EffectiveSourceInsertions[numFinalParticles];
    outMoms = Table[Symbol["k" <> ToString[i]], {i, 1, numFinalParticles}];
    FCFAConvert[
      CreateFeynAmp[insertions],
      IncomingMomenta -> {p},
      OutgoingMomenta -> outMoms,
      UndoChiralSplittings -> True,
      ChangeDimension -> D,
      List -> False,
      SMP -> True,
      Contract -> True,
      DropSumOver -> True
    ]
  ];

(* D30SourcePolarizationCanonicalize[expr]
   =======================================
   Summary
     Rewrite source-model polarization labels into the outgoing-momentum
     convention used elsewhere in the package.

   Parameters
     expr : expression
       D30 source amplitude or subexpression.

   Returns
     expression
       Canonicalized expression.

   Notes
     This is a convention bridge.  The underlying physics is unchanged, but the
     software needs one consistent sign convention so the generic polarization
     and kinematic helpers can be reused without D30-specific branches. *)
D30SourcePolarizationCanonicalize[expr_] :=
  expr /. Polarization[-mom_, phase_] :> Polarization[mom, phase];

(* D30SourceCanonicalKinematicRules[numFinalParticles]
   ===================================================
   Summary
     Return the additional scalar-product identities involving the incoming
     source momentum `p`.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     list
       Replacement rules from `Pair[p, ki]` structures to antenna invariants.

   Notes
     These rules are written explicitly rather than derived on the fly because
     they define the physics bridge from the source-process picture to the
     massless antenna invariant language used by the rest of the code base. *)
D30SourceCanonicalKinematicRules[2] :=
  {
    Pair[Momentum[p, _], Momentum[p, _]] -> q2,
    Pair[Momentum[p, _], Momentum[k1, _]] -> q2 / 2,
    Pair[Momentum[k1, _], Momentum[p, _]] -> q2 / 2,
    Pair[Momentum[p, _], Momentum[k2, _]] -> q2 / 2,
    Pair[Momentum[k2, _], Momentum[p, _]] -> q2 / 2
  };

D30SourceCanonicalKinematicRules[3] :=
  {
    Pair[Momentum[p, _], Momentum[p, _]] -> q2,
    Pair[Momentum[p, _], Momentum[k1, _]] -> (s12 + s13) / 2,
    Pair[Momentum[k1, _], Momentum[p, _]] -> (s12 + s13) / 2,
    Pair[Momentum[p, _], Momentum[k2, _]] -> (s12 + s23) / 2,
    Pair[Momentum[k2, _], Momentum[p, _]] -> (s12 + s23) / 2,
    Pair[Momentum[p, _], Momentum[k3, _]] -> (s13 + s23) / 2,
    Pair[Momentum[k3, _], Momentum[p, _]] -> (s13 + s23) / 2
  };

D30SourceCanonicalKinematicRules[_] :=
  {};

(* D30SourceMassRules[]
   ====================
   Summary
     Return the source-process mass substitutions used in the D30 convention
     bridge.

   Returns
     list
       Rules that set the gluino mass to zero and identify the neutralino mass
       squared with `q2`.

   Notes
     The D30 effective source is only an intermediate construction device.  The
     route ultimately targets a massless antenna convention, so these
     substitutions make that limiting interpretation explicit. *)
D30SourceMassRules[] :=
  {MGl -> 0, MNeu^2 -> q2};

(* D30SourceAmplitudeTerms[numFinalParticles]
   ==========================================
   Summary
     Expand the source amplitude into individual terms for pairwise
     self-interference construction.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     list
       Expanded amplitude terms.

   Notes
     The route interferes terms pairwise so diagonal and off-diagonal
     contributions can be counted transparently.  That is physically useful
     when debugging which interference channel is responsible for a mismatch. *)
D30SourceAmplitudeTerms[numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  AmplitudeTerms[
    Expand[D30SourcePolarizationCanonicalize[D30EffectiveSourceAmplitude[
      numFinalParticles]]]
  ];

(* D30SourceRenameSUNIndices[expr]
   ===============================
   Summary
     Rename explicit colour indices in one copy of a source amplitude before
     multiplying it by another copy.

   Parameters
     expr : expression
       One amplitude term or amplitude copy.

   Returns
     expression
       Expression with fresh SUN indices.

   Notes
     This is a software fix for a real colour-algebra issue: without distinct
     dummy indices, self-interference products can violate Einstein summation
     assumptions and produce spurious contractions. *)
D30SourceRenameSUNIndices[expr_] :=
  Module[{indices, rules},
    indices =
      DeleteDuplicates[
        Cases[
          expr,
          head_Symbol[sym_Symbol] /; SymbolName[head] === "SUNIndex" :>
            head[sym],
          Infinity
        ]
      ];
    rules =
      Thread[
        indices ->
          (indices /. head_[sym_Symbol] :>
            head[Unique[SymbolName[sym] <> "$r"]])
      ];
    expr /. rules
  ];

(* D30SourceInterferencePair[leftTerm, rightTerm, numFinalParticles]
   =================================================================
   Summary
     Evaluate one interference contribution between two source-amplitude terms.

   Parameters
     leftTerm, rightTerm : expression
       Source-amplitude terms to interfere.
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Simplified interference contribution in the package’s antenna
       kinematic convention.

   Notes
     This is the heart of the D30 effective-source bridge.  The function
     deliberately follows the same physical sequence one would write by hand:
     choose kinematics, form the conjugate product, perform colour and spin
     sums, sum physical gluon polarizations, then convert to the canonical
     invariant convention.  Keeping that order visible is more valuable here
     than maximizing terseness. *)
D30SourceInterferencePair[leftTerm_, rightTerm_,
   numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{left, bare, summed, polarized, expanded, evaluated, gluonMomenta,
     final},
    KinematicRules[numFinalParticles];
    (* Rename indices only on one side of the product so the resulting colour
       contractions represent the intended independent amplitude copies. *)
    left = D30SourceRenameSUNIndices[leftTerm];
    bare = ComplexConjugate[left] * rightTerm;
    (* Perform colour simplification before the polarization algebra gets too
       large.  This is mainly a usability and performance decision: smaller
       intermediate expressions are much easier to diagnose later. *)
    summed =
      bare //
      SUNSimplify[#, Explicit -> True, SUNNToCACF -> False]& //
      FermionSpinSum;
    gluonMomenta =
      If[numFinalParticles === 2,
        {k2},
        {k2, k3}
      ];
    polarized =
      Fold[
        SafeDoPolarizationSums[#1, #2, 0, VirtualBoson -> True]&,
        summed,
        gluonMomenta
      ];
    expanded = DiracSigmaExplicit[polarized];
    evaluated = Calc[expanded];
    (* The final replacement chain is the bridge from the source-model algebra
       to the same invariant and epsilon convention used by the rest of the
       antenna package, so D30 can share diagnostics and route infrastructure
       with the A/B/C families. *)
    final =
      evaluated //
      ApplyFeynCalcRules[#, numFinalParticles]& //
      ReplaceAll[D30SourceCanonicalKinematicRules[numFinalParticles]] //
      ReplaceAll[D30SourceMassRules[]] //
      ReplaceAll[CasimirSubs] //
      ReplaceAll[D -> 4 - 2 Epsilon] //
      SUNSimplify //
      Together;
    final
  ];

(* D30SourceSelfInterference[numFinalParticles]
   ============================================
   Summary
     Build the full D30 source self-interference by summing diagonal and
     off-diagonal term pairs.

   Parameters
     numFinalParticles : Integer
       Supported source multiplicity.

   Returns
     expression
       Full source self-interference in canonical package form.

   Notes
     The diagonal/off-diagonal split is explicit on purpose.  Physically it
     mirrors the decomposition of |M|^2 into squares plus interference pieces,
     and software-wise it makes later debugging much easier than hiding the same
     combinatorics inside one double sum. *)
D30SourceSelfInterference[numFinalParticles_Integer /; MemberQ[{2, 3}, numFinalParticles]] :=
  Module[{terms, nTerms, diagonal, offDiagonal, result},
    terms = D30SourceAmplitudeTerms[numFinalParticles];
    nTerms = Length[terms];
    diagonal =
      Sum[
        D30SourceInterferencePair[terms[[i]], terms[[i]], numFinalParticles],
        {i, 1, nTerms}
      ];
    offDiagonal =
      Sum[
        2 D30SourceInterferencePair[terms[[i]], terms[[j]], numFinalParticles],
        {i, 1, nTerms - 1},
        {j, i + 1, nTerms}
      ];
    result =
      diagonal + offDiagonal //
      SUNSimplify //
      Together;
    result
  ];
